<?php

namespace FondOfSpryker\Zed\ProductPageSearchExpander\Communication\Plugin\ProductPageSearch\Elasticsearch\ProductPageData;

use Codeception\Test\Unit;
use Generated\Shared\Transfer\ProductPageSearchTransfer;

class ModelShortDataExpanderPluginTest extends Unit
{
    /**
     * @var \FondOfSpryker\Zed\ProductPageSearchExpander\Communication\Plugin\ProductPageSearch\Elasticsearch\ModelShortDataExpanderPlugin
     */
    protected $plugin;

    /**
     * @var \Generated\Shared\Transfer\ProductPageSearchTransfer|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $productAbstractPageSearchTransfer;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->productAbstractPageSearchTransfer = $this->getMockBuilder(ProductPageSearchTransfer::class)
            ->disableOriginalConstructor()
            ->setMethods(['setModelShort'])
            ->getMock();

        $this->plugin = new ModelShortDataExpanderPlugin();
    }

    /**
     * @return void
     */
    public function testModelShortExpanderPluginTestSuccess(): void
    {
        $this->productAbstractPageSearchTransfer->expects($this->once())
            ->method('setModelShort');

        $this->plugin->expandProductPageData([
            'attributes' => json_encode(['model_short' => 'test']),
        ], $this->productAbstractPageSearchTransfer);
    }

    /**
     * @return void
     */
    public function testModelShortExpanderPluginTestFailed(): void
    {
        $this->productAbstractPageSearchTransfer->expects($this->never())
            ->method('setModelShort');

        $this->plugin->expandProductPageData([
            'attributes' => json_encode(['wrong_key' => 'test']),
        ], $this->productAbstractPageSearchTransfer);
    }
}
