<?php

namespace FondOfSpryker\Zed\ProductPageSearchExpander\Communication\Plugin\ProductPageSearch\Elasticsearch\ProductPageData;

use Codeception\Test\Unit;
use Generated\Shared\Transfer\ProductPageSearchTransfer;

class SizeDataExpanderPluginTest extends Unit
{
    /**
     * @var \FondOfSpryker\Zed\ProductPageSearchExpander\Communication\Plugin\ProductPageSearch\Elasticsearch\ProductPageData\SizeDataExpanderPlugin
     */
    protected $plugin;

    /**
     * @var \Generated\Shared\Transfer\ProductPageSearchTransfer|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $productAbstractPageSearchTransfer;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->productAbstractPageSearchTransfer = $this->getMockBuilder(ProductPageSearchTransfer::class)
            ->disableOriginalConstructor()
            ->setMethods(['setSize'])
            ->getMock();

        $this->plugin = new SizeDataExpanderPlugin();
    }

    /**
     * @return void
     */
    public function testSizeExpanderPluginTestSuccess(): void
    {
        $this->productAbstractPageSearchTransfer->expects($this->once())
            ->method('setSize');

        $this->plugin->expandProductPageData([
            'attributes' => json_encode(['size' => 'test']),
        ], $this->productAbstractPageSearchTransfer);
    }

    /**
     * @return void
     */
    public function testSizeExpanderPluginTestFailed(): void
    {
        $this->productAbstractPageSearchTransfer->expects($this->never())
            ->method('setSize');

        $this->plugin->expandProductPageData([
            'attributes' => json_encode(['wrong_key' => 'test']),
        ], $this->productAbstractPageSearchTransfer);
    }
}
